export const GET_MERCHANT_LIST_PENDING = 'GET_MERCHANT_LIST_PENDING'
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS'
export const GET_MERCHANT_LIST_ERROR = 'GET_MERCHANT_LIST_ERROR'

export const GET_TAX_PENDING = 'GET_TAX_PENDING'
export const GET_TAX_SUCCESS = 'GET_TAX_SUCCESS'
export const GET_TAX_ERROR = 'GET_TAX_ERROR'

export const GET_SHOPS_LIST_PENDING = 'GET_SHOPS_LIST_PENDING'
export const GET_SHOPS_LIST_SUCCESS = 'GET_SHOPS_LIST_SUCCESS'
export const GET_SHOPS_LIST_ERROR = 'GET_SHOPS_LIST_ERROR'

export const GET_SHOP_PRODUCT_LIST_PENDING = 'GET_SHOP_PRODUCT_LIST_PENDING'
export const GET_SHOP_PRODUCT_LIST_SUCCESS = 'GET_SHOP_PRODUCT_LIST_SUCCESS'
export const GET_SHOP_PRODUCT_LIST_ERROR = 'GET_SHOP_PRODUCT_LIST_ERROR'

export const GET_CATEGORY_LIST_PENDING = 'GET_CATEGORY_LIST_PENDING'
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR'
