export const GET_MERCHANT_LIST_PENDING = 'GET_MERCHANT_LIST_PENDING'
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS'
export const GET_MERCHANT_LIST_ERROR = 'GET_MERCHANT_LIST_ERROR'

export const GET_TAX_PENDING = 'GET_TAX_PENDING'
export const GET_TAX_SUCCESS = 'GET_TAX_SUCCESS'
export const GET_TAX_ERROR = 'GET_TAX_ERROR'
