export const GET_MERCHANT_LIST_PENDING = 'GET_MERCHANT_LIST_PENDING'
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS'
export const GET_MERCHANT_LIST_ERROR = 'GET_MERCHANT_LIST_ERROR'

export const GET_TAX_PENDING = 'GET_TAX_PENDING'
export const GET_TAX_SUCCESS = 'GET_TAX_SUCCESS'
export const GET_TAX_ERROR = 'GET_TAX_ERROR'

export const GET_SHOPS_LIST_PENDING = 'GET_SHOPS_LIST_PENDING'
export const GET_SHOPS_LIST_SUCCESS = 'GET_SHOPS_LIST_SUCCESS'
export const GET_SHOPS_LIST_ERROR = 'GET_SHOPS_LIST_ERROR'

export const GET_SHOP_PRODUCT_LIST_PENDING = 'GET_SHOP_PRODUCT_LIST_PENDING'
export const GET_SHOP_PRODUCT_LIST_SUCCESS = 'GET_SHOP_PRODUCT_LIST_SUCCESS'
export const GET_SHOP_PRODUCT_LIST_ERROR = 'GET_SHOP_PRODUCT_LIST_ERROR'

export const GET_CATEGORY_LIST_PENDING = 'GET_CATEGORY_LIST_PENDING'
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR'

export const GET_ADDON_LIST_PENDING = 'GET_ADDON_LIST_PENDING'
export const GET_ADDON_LIST_SUCCESS = 'GET_ADDON_LIST_SUCCESS'
export const GET_ADDON_LIST_ERROR = 'GET_ADDONRY_LIST_ERROR'

export const PLACE_ORDER_PENDING = 'PLACE_ORDER_PENDING'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR'

export const SET_LOCAL_STORAGE = 'SET_LOCAL_STORAGE'
export const SET_PRODUCT = 'SET_PRODUCT'
